--- 
abstract: exciting new weblogging software or something
author: Jonathan Rockway <jrockway@cpan.org>
build_requires: 
  Directory::Scratch: 0.12
  HTML::Tidy: 1.08
  Path::Class: 0
  Test::Exception: 0
  Test::HTML::Tidy: 0
  Test::JSON: 0
  Test::LongString: 0
  Test::More: 0
  Test::NoTabs: 0
  Test::Strict: 0
  Test::WWW::Mechanize::Catalyst: 0.41
  Test::XML::Valid: 0
  Test::YAML::Valid: 0.02
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: GPL
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Angerwhale
no_index: 
  directory: 
    - inc
    - t
requires: 
  Algorithm::IncludeExclude: 0.01
  Catalyst: 5.7
  Catalyst::Component::ACCEPT_CONTEXT: 0.02
  Catalyst::Model::XML::Feed: 0.01
  Catalyst::Plugin::Cache: 0.02
  Catalyst::Plugin::Cache::Store::FastMmap: 0.01
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::ConfigLoader::Environment: 0.01
  Catalyst::Plugin::LogWarnings: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0.7
  Catalyst::View::JSON: 0
  Catalyst::View::Jemplate: 0
  Catalyst::View::TT: 0
  Class::C3: 0
  Compress::Zlib: 2.005
  Crypt::OpenPGP: 1.03
  Crypt::Random: 0
  Data::UUID: 0
  Digest::MD5: 0
  File::Attributes: 0
  File::Attributes::Recursive: 0
  File::CreationTime: 2.03
  File::Find: 0
  File::Path: 0
  File::Remove: 0
  File::Slurp: 9999.12
  File::Spec: 0
  GD::SecurityImage: 0
  HTML::SBC: 0
  HTML::TreeBuilder: 0
  HTTP::Date: 0
  IO::String: 0
  JSON: 0
  Module::Pluggable: 0
  NEXT: 0.60
  POSIX: 0
  Pod::Simple::Text: 0
  Pod::Xhtml: 1.57
  Quantum::Superpositions: 0
  Scalar::Util: 0
  Syntax::Highlight::Engine::Kate: 0.02
  TeX::Hyphen: 0
  Template::Plugin::Filter: 0
  Template::Plugin::JavaScript: 0
  Template::Plugin::Lingua::EN::Inflect: 0
  Text::Autoformat: 0
  Text::Markdown: 0
  Text::Textile: 0
  Text::WikiFormat: 0.77
  Time::Duration: 0
  URI: 0
  URI::Escape: 3.28
  URI::Find: 0
  XML::Atom::SimpleFeed: 0.8
  XML::Feed: 0.11
  YAML: 0.60
  YAML::Syck: 0.71
  base: 0
  version: 0
tests: t/*/*.t
version: 0.061
