abstract: exciting new weblogging software or something
author: Jonathan Rockway <jrockway@cpan.org>
build_requires: 
  Directory::Scratch: 0.12
  HTML::Tidy: 0
  Test::HTML::Tidy: 0
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
  Test::XML::Valid: 0
  Test::YAML::Valid: 0.02
  ok: 0
distribution_type: module
generated_by: Module::Install version 0.640
license: GPL
name: Angerwhale
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.7
  Catalyst::Model::XML::Feed: 0.01
  Catalyst::Plugin::Cache::FastMmap: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::ConfigLoader::Environment: 0.01
  Catalyst::Plugin::DefaultEnd: 0
  Catalyst::Plugin::LogWarnings: 0
  Catalyst::Plugin::Prototype: 0
  Catalyst::Plugin::Scheduler: 0.07
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::File: 0
  Catalyst::Plugin::Setenv: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0.2
  Catalyst::View::TT::ForceUTF8: 0
  Class::C3: 0
  Crypt::Blowfish: 0
  Crypt::CAST5_PP: 0
  Crypt::DES_EDE3: 0
  Crypt::IDEA: 0
  Crypt::OpenPGP: 1.03
  Crypt::RIPEMD160: 0
  Crypt::Random: 1.25
  Crypt::Rijndael: 0
  Crypt::Twofish: 2.00
  Data::GUID: 0.04
  Digest::MD5: 0
  Digest::SHA1: 0
  File::Attributes: 0
  File::Attributes::Recursive: 0
  File::CreationTime: 2.03
  File::Find: 0
  File::Slurp: 9999.12
  File::Temp: 0
  HTML::TreeBuilder: 0
  HTTP::Date: 0
  IO::String: 0
  Module::Pluggable: 0
  NEXT: 0.60
  Pod::Simple::Text: 0
  Pod::Xhtml: 0
  Quantum::Superpositions: 0
  Scalar::Util: 0
  Syntax::Highlight::Engine::Kate: 0
  TeX::Hyphen: 0
  Template::Plugin::Filter: 0
  Template::Plugin::Lingua::EN::Inflect: 0
  Text::Autoformat: 0
  Text::WikiFormat: 0.77
  Time::Duration: 0
  URI: 0
  URI::Escape: 3.28
  XML::Atom::SimpleFeed: 0.8
  XML::Feed: 0.11
  YAML: 0.60
  YAML::Syck: 0.71
  base: 0
  version: 0
tests: t/*/*.t
version: 0.01_02
